Update android_ci_cd.yml

diff --git a/.github/workflows/android_ci_cd.yml b/.github/workflows/android_ci_cd.yml
--- a/.github/workflows/android_ci_cd.yml
+++ b/.github/workflows/android_ci_cd.yml
@@ -53,6 +53,23 @@ jobs:
     - name: Install dependencies
       run: yarn install
 
+        - name: Prepare keystore
+    run: |
+      echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > android/app/my-android-ci-cd.keystore
+      ls -l android/app/
+
+  - name: Debug keystore file
+    run: |
+      if [ -f android/app/my-android-ci-cd.keystore ]; then
+        echo "Keystore file exists."
+      else
+        echo "Keystore file is missing."
+        exit 1
+      fi
+
+  - name: Set keystore permissions
+    run: chmod 600 android/app/my-android-ci-cd.keystore
+
     # Fix: Grant executable permissions for gradlew
     - name: Grant execute permissions for gradlew
       run: chmod +x ./gradlew
